#!/usr/bin/env node
// 可放在仓库内运行，也可单独下载后在 Koishi 根目录运行。启动仅依赖 Node 内置模块。
const fs = require('node:fs')
const path = require('node:path')
const { createRequire } = require('node:module')
const { spawnSync } = require('node:child_process')

const REPOSITORY = 'https://github.com/Catrong/phi-plugin.git'
const WRAPPER_NAME = 'koishi-plugin-phi-plugin'
const WRAPPER_ENTRY = "// Generated by phi-plugin/scripts/install-koishi.cjs\nmodule.exports = require('phi-plugin/koishi')\n"

function parseArgs(args) {
    const options = { root: process.cwd(), repo: REPOSITORY, branch: '', config: 'koishi.yml', update: false, dryRun: false, manager: '' }
    for (let i = 0; i < args.length; i++) {
        const arg = args[i]
        if (arg === '--help' || arg === '-h') return { ...options, help: true }
        if (arg === '--update') options.update = true
        else if (arg === '--dry-run') options.dryRun = true
        else if (['--root', '--repo', '--branch', '--config', '--manager'].includes(arg)) {
            if (!args[i + 1] || args[i + 1].startsWith('--')) throw new Error(`${arg} 缺少参数`)
            options[arg.slice(2)] = args[++i]
        } else throw new Error(`未知参数：${arg}`)
    }
    if (options.manager && !['npm', 'yarn', 'pnpm'].includes(options.manager)) throw new Error('--manager 仅支持 npm、yarn、pnpm')
    return options
}

function run(command, args, cwd, capture = false) {
    // Windows 的包管理器是 .cmd；仅这些固定命令使用 shell，不插入路径或用户参数。
    const packageManager = ['npm', 'yarn', 'pnpm'].includes(command)
    const result = spawnSync(command, args, {
        cwd,
        shell: process.platform === 'win32' && packageManager,
        stdio: capture ? 'pipe' : 'inherit',
        encoding: 'utf8',
        env: { ...process.env, PUPPETEER_SKIP_DOWNLOAD: 'true' },
    })
    if (result.error) throw new Error(`无法执行 ${command}：${result.error.message}`)
    if (result.status !== 0) throw new Error(`${command} 执行失败（退出码 ${result.status}）`)
    return result.stdout || ''
}

function detectManager(root, manifest) {
    const locks = [['package-lock.json', 'npm'], ['yarn.lock', 'yarn'], ['pnpm-lock.yaml', 'pnpm']]
        .filter(([file]) => fs.existsSync(path.join(root, file)))
    if (locks.length === 1) return locks[0][1]
    if (locks.length > 1) throw new Error('存在多种宿主锁文件，请通过 --manager 明确选择包管理器')
    const manager = (manifest.packageManager || '').split('@')[0]
    return ['npm', 'yarn', 'pnpm'].includes(manager) ? manager : 'npm'
}

function readJson(file) {
    return JSON.parse(fs.readFileSync(file, 'utf8'))
}

function loadYaml(root, core) {
    for (const base of [root, core]) {
        try { return createRequire(path.join(base, 'package.json'))('yaml') } catch (error) {
            if (error.code !== 'MODULE_NOT_FOUND') throw error
        }
    }
    throw new Error('安装依赖后仍无法加载 yaml，请检查包管理器输出')
}

// 递归检查分组，只匹配插件键，绝不搜索/输出配置中的密钥等值。
function findEntries(YAML, plugins, predicate, enabled = true, result = []) {
    if (!YAML.isMap(plugins)) throw new Error('plugins 必须是 YAML 映射')
    for (const pair of plugins.items) {
        const key = String(pair.key.value)
        const name = key.replace(/^~/, '').split(':')[0]
        const active = enabled && !key.startsWith('~') && pair.value?.get?.('$if') !== false
        if (name === 'group') findEntries(YAML, pair.value, predicate, active, result)
        else if (predicate(name)) result.push({ pair, name, active })
    }
    return result
}

function configure(YAML, source) {
    const doc = YAML.parseDocument(source)
    if (doc.errors.length) throw new Error('Koishi YAML 配置存在语法错误，请先修复')
    if (!YAML.isMap(doc.contents)) throw new Error('Koishi 配置必须是 YAML 映射')
    if (!doc.has('plugins')) doc.set('plugins', {})
    const plugins = doc.get('plugins', true)
    const existing = findEntries(YAML, plugins, name => name === 'phi-plugin' || /(?:^|\/)phi-plugin\/koishi\.cjs$/.test(name))
    if (existing.length > 1) throw new Error('发现多个 phi-plugin 配置项，请先合并，避免重复响应')
    if (!existing.length) plugins.set('phi-plugin', {})
    else if (existing[0].name !== 'phi-plugin') {
        // 从旧的相对路径入口迁移，保留禁用标记、实例 ID 和完整配置。
        existing[0].pair.key.value = String(existing[0].pair.key.value).replace(existing[0].name, 'phi-plugin')
    }
    const puppeteer = findEntries(YAML, plugins, name => name === 'puppeteer')
    if (!puppeteer.length) plugins.set('puppeteer', {})
    const database = findEntries(YAML, plugins, name => name.startsWith('database-'))
    const notices = []
    if (existing.length && !existing[0].active) notices.push('已有 phi-plugin 处于禁用分组或禁用状态，已保留；请在控制台启用。')
    if (puppeteer.length && !puppeteer.some(item => item.active)) notices.push('Puppeteer 服务已配置但未启用，请在控制台启用。')
    if (!database.some(item => item.active)) notices.push('请在控制台启用一个 database 服务（例如 database-sqlite）。')
    return { content: doc.toString(), notices }
}

function verifyInstallation(root) {
    const requireHost = createRequire(path.join(root, 'package.json'))
    const meta = requireHost(`${WRAPPER_NAME}/package.json`)
    if (meta.name !== WRAPPER_NAME) throw new Error('包装包名称不匹配，控制台无法识别')
    const wrapper = requireHost(WRAPPER_NAME)
    if (wrapper !== requireHost('phi-plugin/koishi') || typeof wrapper.apply !== 'function' || !wrapper.Config) {
        throw new Error('包装入口或 Config 导出验证失败')
    }
}

function install(options, dependencies = {}) {
    const execute = dependencies.run || run
    const root = fs.realpathSync(path.resolve(options.root))
    const hostFile = path.join(root, 'package.json')
    const host = readJson(hostFile)
    const deps = { ...host.devDependencies, ...host.dependencies }
    if (!deps.koishi && !deps['@koishijs/core']) throw new Error('目标目录不是 Koishi 项目，请使用 --root 指定宿主根目录')
    const configFile = path.resolve(root, options.config)
    if (!fs.existsSync(configFile)) throw new Error(`配置文件不存在：${configFile}；可通过 --config 指定 YAML 配置`)
    if (!/\.ya?ml$/i.test(configFile)) throw new Error('目前只支持 YAML 格式的 Koishi 配置')
    const core = path.join(root, 'external', 'phi-plugin')
    const wrapper = path.join(root, 'external', WRAPPER_NAME)
    const wrapperFile = path.join(wrapper, 'package.json')
    const entryFile = path.join(wrapper, 'index.cjs')
    if (fs.existsSync(wrapper)) {
        if (!fs.existsSync(wrapperFile) || readJson(wrapperFile).name !== WRAPPER_NAME
            || !fs.existsSync(entryFile) || !/module\.exports\s*=\s*require\(['"]phi-plugin\/koishi['"]\)/.test(fs.readFileSync(entryFile, 'utf8'))) {
            throw new Error(`包装目录已被其他代码占用：${wrapper}；请先迁移旧插件，安装器不会覆盖`)
        }
    }
    if (fs.existsSync(core) && (!fs.existsSync(path.join(core, 'package.json')) || readJson(path.join(core, 'package.json')).name !== 'phi-plugin')) {
        throw new Error(`插件目录被其他内容占用：${core}`)
    }
    const manager = options.manager || detectManager(root, host)
    console.log(`Koishi：${root}\n本体：${core}\n包装包：${wrapper}\n包管理器：${manager}`)
    if (options.dryRun) {
        console.log(`预览：${fs.existsSync(core) ? options.update ? '快进更新本体' : '复用已有本体' : '克隆本体'} → 生成包装包 → 安装依赖 → 登记配置。未写入文件。`)
        return
    }
    if (manager === 'yarn') {
        if (Number(execute('yarn', ['--version'], root, true).trim().split('.')[0]) < 2) {
            throw new Error('需要 Yarn 2+ 的 portal 本地链接支持；也可使用 --manager npm')
        }
        if (execute('yarn', ['config', 'get', 'nodeLinker'], root, true).trim() !== 'node-modules') {
            throw new Error('Koishi 包扫描需要 node_modules，请先将 Yarn nodeLinker 设置为 node-modules')
        }
    }
    if (!fs.existsSync(core)) {
        fs.mkdirSync(path.dirname(core), { recursive: true })
        execute('git', ['clone', '--depth=1', ...(options.branch ? ['--branch', options.branch] : []), '--', options.repo, core], root)
    } else if (options.update) {
        if (!fs.existsSync(path.join(core, '.git'))) throw new Error('本体不是 Git 仓库，不能自动更新')
        if (execute('git', ['status', '--porcelain'], core, true).trim()) throw new Error('本体有未提交修改，已停止更新；提交或保存修改后重试')
        execute('git', ['pull', '--ff-only'], core)
    }
    const coreMeta = readJson(path.join(core, 'package.json'))
    if (coreMeta.name !== 'phi-plugin' || !fs.existsSync(path.join(core, 'koishi.cjs'))) throw new Error('该 phi-plugin 版本没有 Koishi 入口，请更新到支持双平台的版本')
    const before = fs.readFileSync(path.join(core, 'package.json'))
    const backup = path.join(root, '.phi-plugin-install-backups', `${Date.now()}-${process.pid}`)
    fs.mkdirSync(backup, { recursive: true, mode: 0o700 })
    for (const [label, file] of [
        ['package.json', hostFile], ['koishi.yml', configFile], ['wrapper-package.json', wrapperFile], ['wrapper-index.cjs', entryFile],
        ...['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'].map(name => [name, path.join(root, name)]),
    ]) {
        if (fs.existsSync(file)) fs.writeFileSync(path.join(backup, label), fs.readFileSync(file), { mode: 0o600 })
    }
    console.log(`原文件备份：${backup}`)
    const protocol = manager === 'yarn' ? 'portal:' : manager === 'pnpm' ? 'link:' : 'file:'
    fs.mkdirSync(wrapper, { recursive: true })
    fs.writeFileSync(wrapperFile, JSON.stringify({
        name: WRAPPER_NAME, version: coreMeta.version, private: true,
        description: 'phi-plugin 的 Koishi 本地包装入口', main: 'index.cjs', license: coreMeta.license || 'ISC',
        dependencies: { 'phi-plugin': `${protocol}../phi-plugin` },
        peerDependencies: { koishi: '^4.18.11' },
        koishi: { service: { required: ['database', 'puppeteer'] } },
    }, null, 2) + '\n')
    fs.writeFileSync(entryFile, WRAPPER_ENTRY)
    host.dependencies ||= {}
    host.dependencies[WRAPPER_NAME] = `${protocol}./external/${WRAPPER_NAME}`
    host.dependencies['phi-plugin'] = `${protocol}./external/phi-plugin`
    if (!deps['koishi-plugin-puppeteer']) host.dependencies['koishi-plugin-puppeteer'] = '^3.9.0'
    fs.writeFileSync(hostFile, JSON.stringify(host, null, 2) + '\n')
    // pnpm link 不安装目标依赖；在本体中独立安装后再链接宿主。
    if (manager === 'pnpm') execute('pnpm', ['install', '--ignore-workspace'], core)
    execute(manager, manager === 'npm' ? ['install', '--ignore-scripts', '--no-audit', '--no-fund'] : ['install'], root)
    if (!before.equals(fs.readFileSync(path.join(core, 'package.json')))) throw new Error('包管理器修改了本体 package.json，请检查安装结果与备份')
    const YAML = (dependencies.loadYaml || loadYaml)(root, core)
    const source = fs.readFileSync(configFile, 'utf8')
    const configured = configure(YAML, source)
    ;(dependencies.verify || verifyInstallation)(root)
    if (source !== configured.content) fs.writeFileSync(configFile, configured.content)
    console.log('安装完成：包装包、插件入口和配置表单已验证。请重启 Koishi 并刷新 WebUI。')
    for (const notice of configured.notices) console.log(notice)
}

if (require.main === module) {
    try {
        const options = parseArgs(process.argv.slice(2))
        if (options.help) console.log(`用法：node install-koishi.cjs [--root Koishi目录] [--update] [--dry-run]\n  --repo URL       首次安装的 Git 仓库（默认 ${REPOSITORY}）\n  --branch 分支    首次克隆指定分支，默认使用远端默认分支\n  --config 文件    相对宿主目录的 YAML 配置，默认 koishi.yml\n  --manager 名称   npm / yarn（2+）/ pnpm；默认优先使用唯一锁文件\n已有本体默认不更新；--update 仅允许干净工作区快进更新。本体 package.json 不作改动。`)
        else install(options)
    } catch (error) {
        console.error(`安装失败：${error.message}\n如已生成备份，可在宿主 .phi-plugin-install-backups 目录恢复原配置。`)
        process.exitCode = 1
    }
}

module.exports = { parseArgs, detectManager, configure, install, verifyInstallation }
